config/routes.rb
Rails.application.routes.draw do

  
  get 'collaborators/create'

  get 'collaborators/destroy'

  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get '/downgrade' => 'registrations#downgrade'
  end

  resources :wikis
  resources :collaborators, only: [:create, :new, :destroy] 

  resources :charges, only: [:new, :create]
  

  

  get 'about' => 'welcome#about'

   root to: 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user


  validates_uniqueness_of :user_id, scope: :wiki_id, message: " is already a collaborator"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :wikis, through: :collaborators
  has_many :collaborators

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,  :confirmable

  after_initialize :set_role

  def admin?
    role == "admin"
  end
  
  def premium_user?
    role == "premium_user"
  end

  def set_role
    self.role ||= 'standard_user'  
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :users, through: :collaborators
  has_many :collaborators

  default_scope { order('wikis.created_at DESC') }
  
  scope :visible_to, -> (user) { user && ((user.role == "admin") || (user.role == "premium_user")) ? all : where(private: false)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  # rescue_from Pundit::NotAuthorizedError do |exception|
  #    redirect_to root_url, alert: exception.message
  # end  

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private
  
  def user_not_authorized
   flash[:alert] ="You are not authorized to perform this action."
   redirect_to(request.referrer || root_path)
 end

   
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end 
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create
    #creating stripe customer object to associating with charge
    customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: 15_00,
      description: "Blocipedia Premium Membership - #{current_user.email}",
      currency: 'usd')

    # raise charge.inspect
    current_user.update_attributes(role: 'premium_user', stripe_id: customer.id)
    flash[:success] = "Thanks for subscribing, #{current_user.email}!"
    redirect_to  root_path

    #Stripe will send back CardErrors, when something goes wrong
    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to  new_charge_path
  end

  def new
    # raise Rails.configuration.stripe.inspect
    @stripe_btn_data = {
      key: "#{Rails.configuration.stripe[:publishable_key]}",
      description: "Blocipedia Premium Membership - #{current_user.name}",
      amount: @amount
    }
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def new
    @users = User.all
    @collaborator = Collaborator.new
  end  
  def create
    @user = User.find(params[:collaborators][:user_id])
    @wiki = Wiki.find(params[:collaborators][:wiki_id])
    @collaborator = Collaborator.new(wiki: @wiki, user: @user)

    if @collaborator.save
      flash[:notice] = "#{@user.name} as a collaborator"
      redirect_to wiki_path(id: params[:collaborators][:wiki_id])
    else
      flash[:error] = @collaborator.errors.full_messages.to_sentence
      render template: "wikis/edit"
    end
       
  end

  def destroy
  
   
     
    @collaborator = Collaborator.find(params[:id])
    @wiki = @collaborator.wiki
    if @collaborator.destroy
      flash[:notice] = "Collaborator was removed successfully"
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "There was an error removing a collaborator.Please try again"  
      render "show"
    end
  end
end  

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def downgrade
    current_user.update_attributes(role: "standard")
    current_user.wikis.each do |wiki|
      wiki.update_attributes(private: false)
    end  
    flash[:success] = "Your premium membership subscription has been cancelled."
    redirect_to root_path
  end  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
   user = User.authenticate(params[:email], params[:password])
  # user = User.authenticate(session_params)
  if user
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in successfully!"
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Signed out successfully"
end  

  # private

  # def session_params
  #   params.require(:session).permit(:email, :password)
  # end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      AuthMailer.test(@user.email, 'Thank you for signing up.').deliver_now
      redirect_to root_url, :notice => "Signed up successfully!"
    else
      render "new", :notice => "Form is invalid"
    end  
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_salt, :password_hash)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki).paginate(page: params[:page], per_page: 10)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was saved"
      redirect_to @wiki
    else
      flash[:notice] = "There was an error saving a wiki. Please try again"
      render "new"
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.all
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki was updated successfully"
      redirect_to @wiki
    else
      flash[:notice] = "There was an error updating a wiki. Please try again" 
      render "edit"
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "Wiki was deleted successfully"
      redirect_to wikis_path
    else
      flash[:notice] = "There was an error deleting a wiki. Please try again"  
      render "show"
    end
  end


  private
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown_to_html(markdown)
  renderer = Redcarpet::Render::HTML.new
  extensions = {fenced_code_blocks: true}
  redcarpet = Redcarpet::Markdown.new(renderer, extensions)
  (redcarpet.render markdown).html_safe
end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<% unless current_user.premium_user? %> 
 <%= form_tag charges_path do %>
   <h1><strong>Upgrade to Premium!</strong></h1>
   <h3> Join the growing ranks of Blocipedia's elite Premium members! With a Premium account, you'll be able to create your own private wikis, select collaborators, and collaborate on other private wikis. You'll also be the first to hear about special Blocipedia events near you! For a limited time, upgrade your account with a one-time payment of just $15!</h3>
 </br>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

<% else %>
<h2>Downgrade Account</h2>
<h4><br>Are you sure you want to lose premium acccess to Blocipedia? <br><br>If you downgrade your account, your private wikis will become public.
</h4>
<br>
<%= link_to "Yes, downgrade my account", downgrade_path, class: 'btn btn-warning', data: { confirm: 'Are you sure you want to downgrade and make all your wikis public?' } %>
<% end %>

app/views/collaborators/new.html.erb
<h1> Add Collaborators </h1>
<%=  form_for :collaborators, url: collaborators_path do |f| %>
  <%= f.hidden_field :wiki_id, :value => params[:wiki_id] %>
  <%= f.select :user_id, options_from_collection_for_select(@users, 'id', 'name') %>
  <%= f.submit "Save" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="navbar-fixed-bottom">
  <div class="text-center">
    <small>
      Anitha Palanisamy © 2015 
    </small>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top ">
  <div class="container-fluid head-style">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-header-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand" >
        <%= link_to image_tag(""), root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-header-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="nav-hover"><%= link_to "Home", root_path %></li>
        <li class="nav-hover"><%= link_to "About", about_path %></li>
        <li class="nav-hover"><%= link_to "Wikis", wikis_path %></li>
      </ul>

      <div class="user-info navbar-right">
        <ul>
          <% if current_user %>
            Hello <%= current_user.name %>!
            <%= link_to edit_user_registration_path, class: 'btn btn-info btn-sm' do %>
            <span class= "glyphicon glyphicon-user"></span>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-warning btn-sm' do %>
            <span class="glyphicon glyphicon-log-out"></span>
            <% end %>
          <% else %>
            <%= link_to "Sign in", new_user_session_path, class: 'sign btn btn-success btn-sm' %>
            <%= link_to "Sign up", new_user_registration_path, class: 'sign btn btn-success btn-sm' %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <meta name= "viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/nav' %>
      <div class="header-spacer"></div>
      <div class="flash-meg row">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>">
            <button type="button" class="close" data-dismiss="alert">&times; </button>
            <%= value %>
          </div>
        <% end %>
      </div>
      <div class="row">
        <div class="row col-md-12 other-content">
          <%= yield %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 foot-size">
          <%= render 'layouts/footer' %>
        </div>
      </div>
    </div>
  </body>  
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
   <div class="alert alert-danger">
      <h4> There are <%= pluralize(@user.errors.count, "error") %> </h4>
      <ul> 
          <% @user.errors.full_messages.each do |msg| %>
            <li> <%= msg %> </li>
          <% end %>
      </ul>
    </div>        
  <% end %>


  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter name" %>
   </div>

   <div class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
  </div>

  <div class="form-group">
    <%= f.label :password %><br />
    <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
  </div>
  
  <div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
  </div>
  
  <div class="form-group">
         <%= f.submit "Sign Up", class: 'btn btn-success' %>
  </div>
 <% end %> 
    
            

        

app/views/welcome/about.html.erb
<h1 class="text-center" >About Blocipedia</h1>
<p class="text-left">Blocipedia is an app, it  provides platform  to create content and collaborate with  team members. 
  It allows content owners to add and remove collaborators, make wikis private or public based on the
   plan they are in.
</p>

app/views/welcome/index.html.erb
<div class="container index-page">
  <div class="row">
    <h2 class="text-center">Blocipedia: Social, Markdown Wikis</h1>
  </div>

  <div class="row text-center">
    <div class="col-md-3">
    </div>
    <div class="col-md-6 content-box">
      <h3> Create and share markdown wikis </h2><br /> <br />
      <div class="btn-group">
       <%= link_to'Sign Up', new_user_registration_path, :class => 'btn btn-large btn-primary' %>
      </div>
    </div>
    <div class="col-md-3">
    </div>
  </div>

  <div class="row text-center">
    <div class="col-md-3">
    </div>
    <% if current_user %>
      <div class="col-md-3"  >
        <div class="point">
          <h4> Create as many public wikis you want! </h4>
          <br>
          <%= link_to('Free Plan', new_user_registration_path, :class => 'btn btn-large btn-primary')  %>
        </div>
      </div>

      <div class="col-md-3">
        <div class="point private-padding">
          <h4>  Create private wikis! </h4><br>
          <%= link_to('Premium Plan', new_charge_path, :class => 'btn btn-large btn-primary')  %>
        </div>
      </div>
    <% end %>

    <div class="col-md-3">
    </div>
  </div >

</div>

app/views/wikis/_form.html.erb
<div class="row">
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%=f.label :title  %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter title" %> <br>
      </div>

      <div class="form-group">
        <%= f.label :body %>

        <div id="epiceditor">
        </div>
        <%= f.hidden_field :body, value: @wiki.body, id: 'epiceditor-body'%> 
      </div>
      
      <div class="form-group">   
        <%= f.submit "Save", class: 'btn btn-success', id: 'wiki-form-submit-btn' %>
      </div>
     
      <% if current_user.role == "premium_user" || current_user.role == "admin"  %>
        <div class="form-group">
          <%= f.label :private %>
          <%= f.check_box :private %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-8">
    <h2><span class="main-text-highlight">Markdown</span></h2><hr>
    <p>This editor uses Markdown, a markup language with plain text formatting syntax designed so that it can be
      converted to HTML. If you're new to Markdown, <a href="http://daringfireball.net/projects/markdown/syntax">
      <strong> click here</strong></a> for an overview of the philosophy and syntax.</p>
  </div>
</div>

app/views/wikis/edit.html.erb
<h1> Edit Wiki </h1>
<div class="col-md-2"></div>
<div class="col-md-8">
  <%= render 'wikis/form' %>
  <h3> Manage Collaborators </h3>
  <br />
  <%= link_to "Add Collaborator", new_collaborator_path(wiki_id: @wiki.id), class: 'btn btn-success' %>
  <br/> <br/>
  <table class="table">
    <% @wiki.collaborators.each do |collaborator| %>
      <tr>
        <td>
          <strong> <%= collaborator.user.name %> </strong>
        </td>
        <td>
          <%= link_to "Remove Collaborator", collaborator_path(collaborator.id), method: :delete, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </table>
</div>
<div class="col-md-2"></div>

app/views/wikis/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="text-center"> All Wikis </h2>
  </div>
  <div class="row">
    <div class="col-md-4">
    </div>
    <table class="table table-bordered table-condensed table-striped col-md-4">
      <tbody>
        <% @wikis.each do |wiki| %>
          <tr>
            <% if current_user.present? %>
              <% if wiki.private? %>
                <td class="col-md-2"> <%= link_to  wiki.title, wiki_path(wiki.id) %><small> private </small> </td>
              <% else %>
                <td class="col-md-2"> <%= link_to  wiki.title, wiki_path(wiki.id) %><small> public </small> </td>
              <% end %>
              <td class="col-md-1"> <%= link_to "Edit", edit_wiki_path(wiki), class: 'btn btn success' %> </td>
              <% if current_user.admin? %>
                <td class="col-md-1"> <%= link_to "Delete", wiki, method: :delete, class: 'btn btn danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %> </td>
              <% end %>
            <% else %>
              <td class="col-md-2"> <%= link_to  wiki.title, wiki_path(wiki.id) %> </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <p class="text-left">
      <%= will_paginate @products %>
    </p>
    <div class="col-md-4">
    </div>
  </div>

  <div class="row text-center">
    <% if policy(Wiki.new).create? %>
      <%= link_to "New Wiki", new_wiki_path, :class => 'btn btn-large btn-primary' %>
    <% end %>
  </div>
</div>

app/views/wikis/new.html.erb
<h1> New Wiki </h1>
<div class="row">
  <%= render 'wikis/form' %>
</div>

app/views/wikis/show.html.erb
<div class="media">
  <div class= "media-body">
    <div class="panel panel-default panel-info">
      <div class="panel-heading text-center"> <%=  markdown_to_html @wiki.title.titleize %> </div>
      <div class="panel-body text-justify">
        <p class="text-justify"> <%= markdown_to_html @wiki.body %> </p>
        <div>
          <%= link_to "Back", wikis_path, class: 'btn btn success'  %>
          <% if current_user.present? %>
            <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn success' %>
            <% if policy(@wiki).destroy? %>
              <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<div>